alias: Alarm Clock Trigger
initial_state: True
hide_entity: False
trigger:
  - platform: template
    value_template: "{% if is_state(now().strftime('%-H:%-M'), states.input_select.alarm_clock_time.state) %}true{% endif %}"
condition:
  - condition: state
    entity_id: input_boolean.alarm_clock
    state: "on"
action: 
  - service: notify.ben
    data_template:
      message: "Alarm Clock Triggered"
    data:
      data:
        tag: 'alarm_trigger'
        actions:
        - action: "activate_siren"
          title: "activate siren"
  - service: light.turn_on
    data:
      entity_id:
       - light.floor_lamp
      brightness: 255
      color_temp: 196
      rgb_color: [255,0,0]
  - service: light.turn_on
    data:
      entity_id:
       - light.jar_leds_template
      #brightness: 255
      #color_temp: 196
      #rgb_color: [255,0,0]
      effect: "Police All"
      #transition: 20