alias: "Away Global Actions"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: input_select.ben_status
    state: "Away"
  - platform: state
    entity_id: input_select.cailin_status
    state: "Away"
condition:
  - condition: template
    value_template: "{% if states('input_select.ben_status') == 'Away' and states('input_select.cailin_status') == 'Away' %}true{% else %}false{% endif %}"
  - condition: state
    entity_id: input_boolean.presence_lockout
    state: "off"
action:
  - service: light.turn_off
    data:
      entity_id: group.all_lights
      transition: 15
  - service: switch.turn_off
    data:
      entity_id:
        - switch.fishstick
        - switch.fan
        - switch.camera_light
        - switch.bedroom_lamp
        - switch.monitor_light
        - switch.wake_on_lan
        - switch.homeseer_hsws100_wall_switch_switch_7_0
  - service: alarm_control_panel.alarm_arm_away