alias: "Back Door Open"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: sensor.back_door_sensor_template
    from: "closed"
    to: "open"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.presence_lockout
      state: "off"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.front_door_right
       - light.front_door_left
       - light.back_door
      brightness: 255
      color_temp: 200
      rgb_color: [255,255,255]
      transition: 5
  - service: notify.ben
    data_template:
      title: "Back Door Open"
      message:  "Somebody took Caesium outside?" 