alias: "Home Announce"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: sensor.xandem
    state: "motion detected"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.presence_lockout
      state: "off"
    - condition: template
      value_template: "{% if as_timestamp(now()) - as_timestamp(states.input_boolean.ha_uptime.last_changed) > 301%}true{% else %}false{% endif %}"
    - condition: template
      value_template: "{% if as_timestamp(now()) - as_timestamp(states.automation.home_announce.last_updated) > 301%}true{% else %}false{% endif %}"
    - condition: or
      conditions:
      - condition: template
        value_template: '{% if as_timestamp(now()) - as_timestamp(states.input_select.ben_status.last_changed) < 300 and states.input_select.ben_status.state == "Home" %}true{% else %}false{% endif %}'
      - condition: template
        value_template: '{% if as_timestamp(now()) - as_timestamp(states.input_select.cailin_status.last_changed) < 300 and states.input_select.cailin_status.state == "Home" %}true{% else %}false{% endif %}'
action:
  - service: tts.google_say
    entity_id:
      - media_player.kitchen_home
      - media_player.bedroom_home
    data_template:
      message: >
        {% if as_timestamp(now()) - as_timestamp(states.input_select.ben_status.last_changed) < 300 and as_timestamp(now()) - as_timestamp(states.input_select.cailin_status.last_changed) < 300%}
        Welcome home Benjamin and Kay-Lin!
        {% elif as_timestamp(now()) - as_timestamp(states.input_select.ben_status.last_changed) < 300%}
        Welcome home Benjamin!
        {% elif as_timestamp(now()) - as_timestamp(states.input_select.cailin_status.last_changed) < 300%}
        Welcome home Kay-Lin!
        {% else %}
        This automation is confused! 
        {% endif %}
  - service: notify.ben
    data_template:
      title: "Arrival"
      message: >
        {% if as_timestamp(now()) - as_timestamp(states.input_select.ben_status.last_changed) < 300 and as_timestamp(now()) - as_timestamp(states.input_select.cailin_status.last_changed) < 300%}
        Welcome home Benjamin and Cailin!
        {% elif as_timestamp(now()) - as_timestamp(states.input_select.ben_status.last_changed) < 300%}
        Welcome home Benjamin!
        {% elif as_timestamp(now()) - as_timestamp(states.input_select.cailin_status.last_changed) < 300%}
        Welcome home Cailin!
        {% else %}
        This automation is confused! 
        {% endif %}