alias: "Home Night"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: input_select.ben_status
    from: "Away"
    to: "Home"
  - platform: state
    entity_id: input_select.cailin_status
    from: "Away"
    to: "Home"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.presence_lockout
      state: "off"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: or
      conditions:
###############If one of us have been home for more than 5 minutes, don't fire
      - condition: template
        value_template: '{% if as_timestamp(now()) - as_timestamp(states.input_select.ben_status.last_changed) < 300 and states.input_select.cailin_status.state != "Home" %}true{% else %}false{% endif %}'
      - condition: template
        value_template: '{% if as_timestamp(now()) - as_timestamp(states.input_select.cailin_status.last_changed) < 300 and states.input_select.ben_status.state != "Home" %}true{% else %}false{% endif %}'
      - condition: template
        value_template: '{% if as_timestamp(now()) - as_timestamp(states.input_select.ben_status.last_changed) < 300 and as_timestamp(now()) - as_timestamp(states.input_select.cailin_status.last_changed) < 300 %}true{% else %}false{% endif %}'
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.switch
       - light.wall
       - light.sink
       - light.front_door_right
       - light.front_door_left
       - light.back_door
       - light.floor_lamp
      brightness: 255
      color_temp: 196
      rgb_color: [255,255,255]
      transition: 5
  - service: alarm_control_panel.alarm_disarm