<<<<<<< HEAD
alias: Media Stopped Night
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.living_room
    state: "off"
action:
  - service: light.turn_on
    data:
      entity_id: light.lr_wall_color_lifx
      brightness: 255
      color_temp: 200
      rgb_color: [255,255,255]
      transition: 15
  - service: light.turn_on
    data:
      entity_id: light.lr_switch_color_lifx
      brightness: 255
      color_temp: 200
      rgb_color: [255,255,255]
=======
alias: Media Stopped Night
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.living_room
    state: "off"
action:
  - service: light.turn_on
    data:
      entity_id: light.lr_wall_color_lifx
      brightness: 255
      color_temp: 200
      rgb_color: [255,255,255]
      transition: 15
  - service: light.turn_on
    data:
      entity_id: light.lr_switch_color_lifx
      brightness: 255
      color_temp: 200
      rgb_color: [255,255,255]
>>>>>>> 7ea084b2d93918d544091323ccfdea995a0fc8c6
      transition: 15