alias: Arlo Record Porch Escalate Automation
initial_state: True
hide_entity: False
trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
     action: activate_siren
action:
  - service: notify.ben
    data:
      title: "ALARM SOUND"
      message: "The alarm sound has been activated"
  - service: tts.google_say
    entity_id:
      - media_player.kitchen_home
      - media_player.bedroom_home
    data_template:
      message: "Alarm triggered by {{ trigger.entity_id }}. You weren't very sneaky! Please leave." 