alias: "Bilnd Tilt"
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: input_slider.blind_tilt
action:
  - service: mqtt.publish
    data_template:
      topic: "bruh/blind1/cover/set"
      payload: '{"tilt": {{ trigger.to_state.state | int }}}'