alias: Minimote 2 Button 4 Short Press
initial_state: True
hide_entity: True
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_34
      scene_id: 7
action:
  - service: switch.turn_off
    data:
      entity_id:
       - switch.monitor_light
