alias: Minimote 2 Button 4 Long Press
initial_state: True
hide_entity: True
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_34
      scene_id: 8
action:
  - service: input_boolean.toggle
    data:
      entity_id: input_boolean.tv_power
