alias: Minimote 1 Button 4 Long Press
initial_state: True
hide_entity: True
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_33
      scene_id: 8
action:
  - service: switch.turn_off
    data:
      entity_id:
       - switch.wake_on_lan
       - switch.fishstick
       - switch.fan
  - service: light.turn_off
    data:
      entity_id:
       - light.megadesk
       - light.boob_1
       - light.boob_2
      transition: 1