alias: Minimote Button 3 Short Press
initial_state: True
hide_entity: True
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: minimote_1_6
      scene_id: 5
action:
  - service: switch.turn_on
    data:
      entity_id:
       - switch.monitor_light