alias: Minimote Button 4 Short Press
initial_state: True
hide_entity: True
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: minimote_1_6
      scene_id: 7
action:
  - service: switch.turn_off
    data:
      entity_id:
       - switch.monitor_light
