alias: Minimote 1 Button 1 Short Press
initial_state: True
hide_entity: True
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_33
      scene_id: 1
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.megadesk
       - light.boob_1
       - light.boob_2
      brightness: 255
      color_temp: 200
      rgb_color: [255,255,255]
      transition: 1