alias: Minimote Button 2 Long Press
initial_state: True
hide_entity: True
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: minimote_1_6
      scene_id: 4
action:
  - service: light.turn_off
    data:
      entity_id:
       - light.megadesk
       - light.boob_1
       - light.boob_2