alias: Dash Bounty Toggle Automation
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: input_boolean.dash_bounty_toggle
action:
  - service_template: >
      {% if is_state('input_boolean.dash_bounty_toggle', 'on') %}
        script.dash_bounty_on
      {% else %}
        script.dash_bounty_off
      {% endif %}