alias: "Porch Animation Speed"
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: input_slider.jar_animation_speed
action:
  - service: mqtt.publish
    data_template:
      topic: "bruh/nightstand/set"
      payload: '{"transition":{{ trigger.to_state.state | int }}}'