alias: Media Paused Night
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.living_room
    state: "paused"
  - platform: state
    entity_id: media_player.kodi
    state: "paused"
condition:
  - condition: state
    entity_id: input_boolean.media_lockout
    state: "off"
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.sink
      brightness: 50
      color_temp: 196
      rgb_color: [255,255,255]
      transition: 15