alias: Media Stopped Night
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.living_room
    state: "off"
  - platform: state
    entity_id: media_player.kodi
    state: "off"
  - platform: state
    entity_id: media_player.kodi
    state: "idle"
condition:
  - condition: state
    entity_id: input_boolean.media_lockout
    state: "off"
  - condition: sun
    after: sunset
    after_offset: "-1:00:00"
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.switch
       - light.wall
       - light.sink
      brightness: 255
      color_temp: 196
      rgb_color: [255,255,255]
      transition: 15