alias: Media Playing Night
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.living_room
    state: "playing"
  - platform: state
    entity_id: media_player.kodi
    state: "playing"
condition:
  - condition: state
    entity_id: input_boolean.media_lockout
    state: "off"
  - condition: sun
    after: sunset
    after_offset: "-1:00:00"
action:
  - service: light.turn_off
    data:
      entity_id:
       - light.switch
       - light.sink
      transition: 15
  - service: light.turn_on
    data:
      entity_id:
       - light.wall
      brightness: 125
      color_temp: 196
      rgb_color: [255,255,255]
      transition: 15